# Generated by Django 5.2.1 on 2025-05-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conductor",
            options={"verbose_name": "Conductor", "verbose_name_plural": "Conductors"},
        ),
        migrations.AlterModelOptions(
            name="guest",
            options={"verbose_name": "Guest", "verbose_name_plural": "Guests"},
        ),
        migrations.AddField(
            model_name="conductor",
            name="instrument",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="guest",
            name="instrument",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
