# Generated by Django 5.2.1 on 2025-05-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0002_alter_conductor_options_alter_guest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="venue",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="venue",
            name="contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="venue",
            name="state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="venue",
            name="zip_code",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
