# Generated by Django 5.2.1 on 2025-05-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0003_alter_venue_address_alter_venue_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conductor",
            name="instrument",
        ),
    ]
